### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by drastick** [c58/marsdb-angular#1]
When trying to add the "MarsDB" dependency to my module I get the following error:

`Failed to instantiate module MarsDB due to:
TypeError: Collection.defaultDelegate is not a function
    at createCollectionDelegate (http://localhost:8100/lib/marsdb-angular/build/marsdb.angular.js:29:37)`

I am including the following files after angular.

```
<script src="lib/marsdb/build/marsdb.polyfills.js"></script>
<script src="lib/marsdb/build/marsdb.min.js"></script>
<script src="lib/marsdb-angular/build/marsdb.angular.js"></script>
```

**Comment by c58** [comment]
Hi, @drastick 
It seems like you are using not latest version of MarsDB. The latest version is 0.5.22. Please upgrade to it and try again. Let me know if it helps ;)

**Comment by drastick** [comment]
Yeah that seemed to fix it.  Appears that I needed to add #master to the end of the url so that bower would pull the latest version.

**Comment by c58** [comment]
Oh, bower.... I forgot to make a release. I will fix it :)
